[firebird]
host = "192.168.100.1"  # La IP que ya comprobaste con telnet
database = 'D:\Microsip datos\UGRPG DAB.FDB' # Ruta local vista desde el servidor
user = "SYSDBA"
password = "mirra19"
charset = "NONE"
dll_path = 'C:\Program Files\Firebird\Firebird_3_0\fbclient.dll'